name: ストーリー系：ストーリー
description: ストーリーのアイデアはこちら
title: "[ストーリー系：ストーリー] <ここにタイトルを入力>"
labels: [ストーリー系：ストーリー]
body:
- type: markdown
  attributes:
    value: |
      ## アイデアのご協力ありがとうございます。
      以下の質問をできる限り埋めていただき、アイデアをなるべく正確にお伝えください
- type: dropdown
  id: ItemType
  attributes:
    label: 提案する部分
    options:
      - 展開について
      - 世界観について
      - キャラについて
      - その他
- type: input
  id: Title
  attributes:
    label: タイトル
    description: 提案内容を一言で表すなら
- type: textarea
  id: IdeaDescription
  attributes:
    label: アイデア説明
    description: アイデアの説明を入れてください
- type: textarea
  id: IdeaStart
  attributes:
    label: アイデアの根拠
    description: どのような理由で、そのアイデアをＴＵＳＢＡＤのストーリーに提案しようと思いましたか？
