name: 建築系：建造物
description: 建造物のアイデアはこちら
title: "[建築系：建造物] <ここにタイトルを入力>"
labels: [建築系：建造物]
body:
- type: markdown
  attributes:
    value: |
      ## アイデアのご協力ありがとうございます。
      以下の質問をできる限り埋めていただき、アイデアをなるべく正確にお伝えください
- type: textarea
  id: Dimension
  attributes:
    label: 建築ディメンション
    description: 実際に建築を行うディメンション名を入れてください
- type: textarea
  id: IdeaName
  attributes:
    label: 建造物名
    description: 建造してほしい島や建築物の名前を入れてください
- type: textarea
  id: IdeaDescription
  attributes:
    label: アイデア説明
    description: 建築物の設定やストーリー、イメージ、コンセプトを入れてください
- type: textarea
  id: designIdea
  attributes:
    label: 外部構想
    description: 、モチーフなどがあればそれの説明や、外部構造、建材を書いてください
- type: textarea
  id: gimmickIdea
  attributes:
    label: 内部構想
    description: 建築物の内部の説明やギミック、スポーンする敵、仕掛けの案、報酬、発生するイベントなどがあれば書いてください
- type: textarea
  id: appeal
  attributes:
    label: アピールポイント
    description: この島を訪れる目的や、訪れたら何が起きるか、訪れる目的があるかなどがあれば記入してください
- type: textarea
  id: routeIdea
  attributes:
    label: レベルイメージ
    description: 攻略難度や難所、攻略手順などのバランス的イメージがあれば書いてください
- type: textarea
  id: uniquePoint
  attributes:
    label: 特筆事項
    description: 項目にない特筆事項があれば書いてください。
