name: アイテム系：ツール
description: 武器や道具のアイデアはこちら
title: "[アイテム系：ツール] <ここにタイトルを入力>"
labels: [アイテム系：ツール]
body:
- type: markdown
  attributes:
    value: |
      ## アイデアのご協力ありがとうございます。
      以下の質問をできる限り埋めていただき、アイデアをなるべく正確にお伝えください
- type: checkboxes
  id: newItem
  attributes:
    label: そのツールはマイクラに存在しないカテゴリのツールですか？
    options:
      - label: はい、杖や鎌など、新しいタイプのツールです。
- type: input
  id: ItemType
  attributes:
    label: 種類
    description: 具体的なツールの種類を書いてください（例：剣、ハサミ、斧…「鎌」や「杖」）
- type: input
  id: OriginalItem
  attributes:
    label: 元アイテムＩＤ
    description: このアイテムを作成する元となるアイテムＩＤまたはアイテム名を正確に入力してください、空欄の場合こちらで確定します。
- type: input
  id: ItemName
  attributes:
    label: アイテム名【入力推奨】
    description: アイテムの名前を入れてください（空欄の場合元アイテムの名前が使われます）
- type: textarea
  id: ItemDescription
  attributes:
    label: アイテム説明
    description: アイテムの説明を入れてください
- type: textarea
  id: ItemTextStyle
  attributes:
    label: 名前、説明書式
    description: アイテムの説明や名前の文字色やスタイルに変更があれば入れてください
- type: checkboxes
  id: useSituation
  attributes:
    label: アイテムの用途カテゴリ（複数選択可能）
    options:
      - label: 近距離攻撃
      - label: 遠距離攻撃
      - label: 採取（伐採、採掘など）
      - label: スキルの発生源
      - label: その他
- type: textarea
  id: useImage
  attributes:
    label: 使用用途やイメージ
    description: どのようなタイミングでどのように使うのかイメージがあれば書いてください
    placeholder: |
     例：攻撃速度が早いので、攻撃回数を稼ぎたい時に使用する
     例：持つと移動速度が遅くなるが、攻撃力が非常に高いので一撃必殺を狙える
- type: textarea
  id: story
  attributes:
    label: 設定など
    description: アイテムにストーリーや設定、またそれに基づいて入手タイミングなどに希望がある場合記入してください
- type: textarea
  id: enchant
  attributes:
    label: エンチャント
    description: 付与したいエンチャントを書いてください
    placeholder: |
     例:ダメージ増加5
- type: checkboxes
  id: hideEnchant
  attributes:
    label: エンチャントの隠蔽
    options:
      - label: はい、付与されているエンチャントを表示しません
- type: textarea
  id: ItemAttribute
  attributes:
    label: 属性
    description: アイテムの属性を記入してください
    placeholder: |
       例：ダメージ+5（メインハンド）
       例：防具+5（オフハンド）
       例：移動速度+10%（メインハンド・オフハンド）
- type: checkboxes
  id: hideAttribute
  attributes:
    label: 属性の隠蔽
    options:
      - label: はい、付与されている属性を表示しません
- type: textarea
  id: ItemDamage
  attributes:
    label: 耐久値損傷度
    description: 耐久値があらかじめ削れている場合は割合、固定値などで記入してください
- type: checkboxes
  id: unbreakable
  attributes:
    label: 不可解のツールですか
    options:
      - label: はい、耐久値無限のツールです
- type: checkboxes
  id: HideUnbreakable
  attributes:
    label: 不可解の隠蔽
    options:
      - label: はい、耐久値無限を表示しません
- type: checkboxes
  id: CutomModel
  attributes:
    label: カスタムモデルの使用
    options:
      - label: はい、アイコンやモデルを変更します。
- type: checkboxes
  id: CutomModelContain
  attributes:
    label: カスタムモデルの存在
    options:
      - label: はい、変更先のアイコンやモデルがもうあります
- type: textarea
  id: uniquePoint
  attributes:
    label: 特筆事項
    description: 項目に存在しない事項があれば書いてください
