name: アイテム系：インスタントアイテム
description: 印板、印玉のアイデアはこちら
title: "[アイテム系：インスタントアイテム] <ここにタイトルを入力>"
labels: [アイテム系：インスタントアイテム]
body:
- type: markdown
  attributes:
    value: |
      ## アイデアのご協力ありがとうございます。
      以下の質問をできる限り埋めていただき、アイデアをなるべく正確にお伝えください
- type: dropdown
  id: ItemType
  attributes:
    label: インスタントアイテムの種類
    options:
      - 印板（看板）
      - 印玉（卵）
      - その他
- type: input
  id: OriginalItem
  attributes:
    label: 元アイテムＩＤ（その他選択時）
    description: このアイテムを作成する元となるアイテムＩＤまたはアイテム名を正確に入力してください、空欄の場合こちらで確定します。
- type: input
  id: ItemName
  attributes:
    label: アイテム名【入力推奨】
    description: アイテムの名前を入れてください
- type: textarea
  id: ItemDescription
  attributes:
    label: アイテム説明
    description: アイテムの説明を入れてください
- type: textarea
  id: ItemTextStyle
  attributes:
    label: 名前、説明書式
    description: アイテムの説明や名前の文字色やスタイルに変更があれば入れてください
- type: textarea
  id: useImage
  attributes:
    label: 使用用途やイメージ
    description: どのようなタイミングでどのように使うのかイメージがあれば書いてください
    value: |
       例：砂利が足りないときに積み上げを行うことで砂利を調達できる
- type: checkboxes
  id: notConsume
  attributes:
    label: 使用した後に消滅せず残るか（印板）
    options:
      - label: はい、印板を壊さない限り何回でも使えます
- type: textarea
  id: story
  attributes:
    label: 設定など
    description: アイテムにストーリーや設定、またそれに基づいて入手タイミングなどに希望がある場合記入してください
- type: textarea
  id: enchant
  attributes:
    label: エンチャント
    description: 付与したいエンチャントを書いてください
    value: |
      例:虫特攻3
- type: checkboxes
  id: hideEnchant
  attributes:
    label: エンチャントの隠蔽
    options:
      - label: はい、付与されているエンチャントを表示しません
- type: textarea
  id: effect
  attributes:
    label: 使用効果
    description: 使用した時の効果を書いてください
    value: |
      例：周辺にいるモブに等しく死を与える
      例：微粒子レベルの確率で苗木が出てくる
      例：必ず的中する嫌な予感を発生させる
- type: textarea
  id: ItemAttribute
  attributes:
    label: 属性
    description: アイテムの属性を記入してください
    value: |
       例：ダメージ+5（メインハンド）
       例：防具+5（オフハンド）
       例：移動速度+10%（メインハンド・オフハンド）
- type: checkboxes
  id: hideAttribute
  attributes:
    label: 属性の隠蔽
    options:
      - label: はい、付与されている属性を表示しません
- type: checkboxes
  id: unbreakable
  attributes:
    label: 不可解のアイテムですか（装飾用）
    options:
      - label: はい、耐久値無限のアイテムです
- type: checkboxes
  id: CutomModel
  attributes:
    label: カスタムモデルの使用
    options:
      - label: はい、アイコンやモデルを変更します。
- type: checkboxes
  id: CutomModelContain
  attributes:
    label: カスタムモデルの存在
    options:
      - label: はい、変更先のアイコンやモデルがもうあります
- type: textarea
  id: uniquePoint
  attributes:
    label: 特筆事項
    description: 項目に存在しない事項があれば書いてください
